# Generated by Django 3.1.1 on 2020-10-02 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lerny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lerny_name', models.CharField(max_length=100, verbose_name='lerny name')),
                ('description', models.CharField(max_length=300, verbose_name='description')),
                ('url_image', models.CharField(max_length=300, verbose_name='url image')),
                ('category', models.CharField(max_length=100, verbose_name='category')),
                ('price', models.FloatField(verbose_name='price')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
            ],
        ),
        migrations.CreateModel(
            name='MicroLerny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('micro_lerny_title', models.CharField(max_length=200, verbose_name='microlerny title')),
                ('micro_lerny_subtitle', models.CharField(max_length=300, verbose_name='microlerny subtitle')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update date')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('lerny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lerny.lerny')),
            ],
        ),
        migrations.CreateModel(
            name='TreeMicroLerny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dady_micro_lerny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dady_micro_lerny', to='lerny.microlerny')),
                ('son_micro_lerny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='son_micro_lerny', to='lerny.microlerny')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.CharField(max_length=300, verbose_name='description')),
                ('content_url', models.CharField(max_length=100, verbose_name='content_url')),
                ('content_type', models.CharField(max_length=200, verbose_name='microlerny title')),
                ('phase', models.CharField(max_length=3, verbose_name='phase')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('points', models.FloatField(verbose_name='points')),
                ('microlerny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lerny.microlerny')),
            ],
        ),
    ]
