# Generated by Django 3.1.2 on 2021-04-14 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lerny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lerny_name', models.CharField(max_length=100, verbose_name='lerny name')),
                ('description', models.CharField(max_length=300, verbose_name='description')),
                ('url_image', models.CharField(max_length=300, verbose_name='url image')),
                ('category', models.CharField(max_length=100, verbose_name='category')),
                ('price', models.FloatField(verbose_name='price')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
            ],
        ),
        migrations.CreateModel(
            name='MicroLerny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('micro_lerny_title', models.CharField(max_length=200, verbose_name='microlerny title')),
                ('micro_lerny_subtitle', models.CharField(max_length=300, verbose_name='microlerny subtitle')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update date')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('lerny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lerny.lerny')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.CharField(max_length=300, verbose_name='description')),
                ('content_url', models.CharField(max_length=100, verbose_name='content_url')),
                ('content_type', models.CharField(max_length=200, verbose_name='microlerny title')),
                ('phase', models.CharField(max_length=3, verbose_name='phase')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('points', models.FloatField(verbose_name='points')),
                ('image_url', models.CharField(max_length=200, verbose_name='image url')),
                ('microlerny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lerny.microlerny')),
            ],
        ),
        migrations.CreateModel(
            name='User_State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_view_date', models.DateTimeField(null=True, verbose_name='last view date')),
                ('lerny_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lerny.lerny')),
                ('micro_lerny_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lerny.microlerny')),
                ('resource_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lerny.resource')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('user_response', models.CharField(max_length=300, null=True, verbose_name='user response')),
                ('response_date', models.DateTimeField(null=True, verbose_name='response date')),
                ('last_view_date', models.DateTimeField(null=True, verbose_name='last view date')),
                ('done_date', models.DateTimeField(auto_now_add=True, verbose_name='done date')),
                ('resource_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lerny.resource')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Micro_Lerny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_microlerny_points', models.FloatField(verbose_name='user microlerny points')),
                ('last_view_date', models.DateTimeField(null=True, verbose_name='last view date')),
                ('micro_lerny_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lerny.microlerny')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Lerny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lerny_points', models.FloatField(verbose_name='lerny points')),
                ('opinion', models.CharField(max_length=300, null=True, verbose_name='opinion')),
                ('opinion_points', models.FloatField(verbose_name='opinion points')),
                ('valor', models.FloatField(verbose_name='valor')),
                ('bill_state', models.BooleanField(default=False)),
                ('reference', models.CharField(max_length=20, verbose_name='reference')),
                ('pay_date', models.DateTimeField(null=True)),
                ('last_view_date', models.DateTimeField(null=True, verbose_name='last view date')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('lerny_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lerny.lerny')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TreeMicroLerny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dady_micro_lerny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dady_micro_lerny', to='lerny.microlerny')),
                ('son_micro_lerny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='son_micro_lerny', to='lerny.microlerny')),
            ],
        ),
    ]
