# Generated by Django 3.1.2 on 2021-04-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lerny', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='microlerny',
            name='microlerny_image_url',
            field=models.CharField(max_length=300, null=True, verbose_name='microlerny image url'),
        ),
    ]
