# Generated by Django 3.1.2 on 2021-04-13 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lerny', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='image_url',
        ),
    ]
