# Generated by Django 3.1.2 on 2021-04-14 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lerny', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='image_url',
            field=models.CharField(default='aqui va la url', max_length=200, verbose_name='image url'),
            preserve_default=False,
        ),
    ]
