# Generated by Django 3.1.2 on 2020-11-19 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lerny', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_micro_lerny',
            old_name='lerny_id',
            new_name='micro_lerny_id',
        ),
        migrations.CreateModel(
            name='User_State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_view_date', models.DateTimeField(null=True, verbose_name='last view date')),
                ('lerny_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lerny.lerny')),
                ('micro_lerny_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lerny.microlerny')),
                ('resource_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lerny.resource')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
