# Generated by Django 3.1.2 on 2021-04-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lerny', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='image_url',
            field=models.CharField(default='Aqui va la url de la imagen', max_length=200, verbose_name='image_url'),
        ),
    ]
