# Generated by Django 3.1.2 on 2021-04-13 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lerny', '0002_remove_resource_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='image',
            field=models.CharField(default='aqui va la url de la imagen del recurso', max_length=200, verbose_name='image'),
            preserve_default=False,
        ),
    ]
