# Generated by Django 3.1.2 on 2021-04-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lerny', '0002_remove_resource_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='image_url',
            field=models.CharField(default='Aqui va la url del recurso', max_length=200, verbose_name='image url'),
            preserve_default=False,
        ),
    ]
