# Generated by Django 3.1.2 on 2020-11-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lerny', '0002_auto_20201118_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lerny',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
