# Generated by Django 3.1.2 on 2021-04-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lerny', '0002_microlerny_microlerny_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='previous_text',
            field=models.CharField(max_length=200, null=True, verbose_name='previous text'),
        ),
    ]
