# Generated by Django 3.1.2 on 2021-05-12 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lerny', '0003_resource_previous_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faqs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_name', models.CharField(max_length=50, verbose_name='intent_name')),
                ('response', models.CharField(max_length=300, verbose_name='response ')),
                ('response_type', models.CharField(max_length=30, null=True, verbose_name='response_type')),
            ],
        ),
        migrations.CreateModel(
            name='Faqs_Lerny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_name', models.CharField(max_length=50, verbose_name='intent_name')),
                ('response', models.CharField(max_length=300, verbose_name='response ')),
                ('url', models.CharField(max_length=300, null=True, verbose_name='url')),
                ('response_type', models.CharField(max_length=30, null=True, verbose_name='response_type')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('subtitle', models.CharField(max_length=100, null=True, verbose_name='subtitle')),
                ('but_name', models.CharField(max_length=30, null=True, verbose_name='but_name')),
                ('lerny_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lerny.lerny')),
            ],
        ),
    ]
