# Generated by Django 3.1.2 on 2020-11-24 03:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lerny', '0003_auto_20201123_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lerny',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
