# Generated by Django 3.1.2 on 2021-05-13 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lerny', '0004_faqs_faqs_lerny'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqs',
            name='response',
            field=models.CharField(max_length=600, verbose_name='response '),
        ),
    ]
