# Generated by Django 3.1.2 on 2021-05-21 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lerny', '0005_auto_20210512_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_lerny',
            old_name='bill_state',
            new_name='active',
        ),
    ]
