# Generated by Django 3.1.2 on 2020-11-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lerny', '0005_auto_20201123_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lerny',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
