# Generated by Django 3.1.2 on 2021-06-03 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lerny', '0006_auto_20210520_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='media_type',
            field=models.CharField(default='file', max_length=200, verbose_name='media type'),
            preserve_default=False,
        ),
    ]
