# Generated by Django 3.1.2 on 2021-06-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lerny', '0007_resource_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(default='consumable', max_length=200, verbose_name='media type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='points',
            field=models.FloatField(null=True, verbose_name='points'),
        ),
    ]
