# Generated by Django 3.1.2 on 2021-06-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lerny', '0008_auto_20210610_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(max_length=200, verbose_name='resource type'),
        ),
    ]
