# Generated by Django 3.1.2 on 2020-11-25 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lerny', '0008_microlerny_micro_lerny_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microlerny',
            name='micro_lerny_url',
        ),
    ]
