# Generated by Django 3.1.2 on 2021-06-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lerny', '0009_auto_20210610_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='first_button',
            field=models.CharField(blank=True, max_length=200, verbose_name='resource type'),
        ),
        migrations.AddField(
            model_name='resource',
            name='second_button',
            field=models.CharField(blank=True, max_length=200, verbose_name='resource type'),
        ),
    ]
