# Generated by Django 3.2.4 on 2021-06-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lerny', '0009_auto_20210610_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=50, verbose_name='nit')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('country', models.CharField(max_length=50, null=True, verbose_name='country')),
                ('region', models.CharField(max_length=50, null=True, verbose_name='region')),
                ('city', models.CharField(max_length=50, null=True, verbose_name='city')),
                ('direction', models.CharField(max_length=100, null=True, verbose_name='direction')),
                ('phone', models.CharField(max_length=50, null=True, verbose_name='phone')),
                ('email', models.CharField(max_length=50, null=True, verbose_name='email')),
                ('web', models.CharField(max_length=50, null=True, verbose_name='web')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
            ],
        ),
    ]
