# Generated by Django 3.1.2 on 2021-06-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lerny', '0010_auto_20210622_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqs',
            name='response_type',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='response_type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faqs_lerny',
            name='but_name',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='but_name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faqs_lerny',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='subtitle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faqs_lerny',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='first_button',
            field=models.CharField(blank=True, max_length=200, verbose_name='first button'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='previous_text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='previous text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='second_button',
            field=models.CharField(blank=True, max_length=200, verbose_name='second button'),
        ),
        migrations.AlterField(
            model_name='user_lerny',
            name='opinion',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='opinion'),
            preserve_default=False,
        ),
    ]
