# Generated by Django 3.1.2 on 2021-06-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lerny', '0011_auto_20210622_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='third_button',
            field=models.CharField(blank=True, max_length=200, verbose_name='third button'),
        ),
    ]
