# Generated by Django 3.2.4 on 2021-06-23 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lerny', '0011_lerny_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_resource',
            name='points',
            field=models.FloatField(null=True, verbose_name='points'),
        ),
    ]
