# Generated by Django 3.2.4 on 2021-07-06 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lerny', '0012_resource_third_button'),
        ('lerny', '0012_user_resource_points'),
    ]

    operations = [
    ]
