# Generated by Django 3.1.2 on 2021-07-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lerny', '0013_merge_20210706_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=200, verbose_name='Correct answer'),
        ),
        migrations.AddField(
            model_name='resource',
            name='correct_answer_button',
            field=models.IntegerField(blank=True, default=1, verbose_name='Correct answer button'),
        ),
        migrations.AddField(
            model_name='resource',
            name='wrong_answer',
            field=models.CharField(blank=True, max_length=200, verbose_name='Wrong answer'),
        ),
    ]
