# Generated by Django 3.1.2 on 2021-07-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lerny', '0014_auto_20210712_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='points',
            field=models.FloatField(blank=True, default=1, verbose_name='points'),
        ),
    ]
