# Generated by Django 3.1.2 on 2021-07-29 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lerny', '0015_auto_20210726_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_url', models.CharField(max_length=100, verbose_name='content_url')),
                ('content_type', models.CharField(max_length=200, verbose_name='microlerny title')),
                ('resource_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lerny.resource')),
            ],
        ),
    ]
