# Generated by Django 3.1.2 on 2021-08-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lerny', '0016_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='position',
            field=models.FloatField(default=1, verbose_name='position'),
            preserve_default=False,
        ),
    ]
