# Generated by Django 3.1.2 on 2021-07-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lerny', '0016_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(max_length=200, verbose_name='content type'),
        ),
    ]
