# Generated by Django 3.1.2 on 2021-07-30 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lerny', '0017_auto_20210729_2051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
    ]
