# Generated by Django 3.1.2 on 2021-09-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lerny', '0018_user_state_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='previous_text',
            field=models.CharField(blank=True, max_length=600, verbose_name='previous text'),
        ),
    ]
