# Generated by Django 3.1.2 on 2021-10-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lerny', '0020_group_user_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_resource',
            name='user_response',
            field=models.TextField(null=True, verbose_name='user response'),
        ),
    ]
