# Generated by Django 3.1.2 on 2021-11-20 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lerny', '0022_auto_20211021_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support_Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('text', models.CharField(max_length=300, verbose_name='response ')),
                ('Response_is_text', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Support_Resource_Microlerny_Lerny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Microlerny_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='micro_lerny_id', to='lerny.microlerny')),
                ('Support_Resource_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lerny.support_resource')),
                ('lerny_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lerny.lerny')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Response', models.CharField(max_length=300, verbose_name='response ')),
                ('Response_Int', models.FloatField(null=True, verbose_name='points')),
                ('Support_Resource_Microlerny_Lerny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lerny.support_resource_microlerny_lerny')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
