# Generated by Django 3.1.2 on 2022-01-28 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lerny', '0025_pqr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pqr',
            name='lerny_id',
        ),
        migrations.RemoveField(
            model_name='pqr',
            name='micro_lerny_id',
        ),
        migrations.RemoveField(
            model_name='pqr',
            name='resource_id',
        ),
        migrations.RemoveField(
            model_name='pqr',
            name='user_id',
        ),
        migrations.AddField(
            model_name='pqr',
            name='user_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lerny.user_state'),
        ),
    ]
