# Generated by Django 3.1.2 on 2022-01-28 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lerny', '0026_auto_20220128_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqr',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pqr',
            name='pqr',
            field=models.TextField(verbose_name='user response'),
        ),
    ]
