# Generated by Django 3.1.2 on 2022-02-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lerny', '0028_auto_20220221_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqr',
            name='type',
            field=models.CharField(choices=[('I', 'Incidente'), ('P', 'Problema'), ('C', 'Consulta'), ('CA', 'Cambio')], max_length=50, null=True),
        ),
    ]
