# Generated by Django 3.1.2 on 2022-02-21 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lerny', '0029_auto_20220221_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqr',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='priority'),
        ),
        migrations.AddField(
            model_name='pqr',
            name='state',
            field=models.BooleanField(default=False, verbose_name='state'),
        ),
        migrations.AddField(
            model_name='pqr',
            name='ticket',
            field=models.CharField(default='ninguno', max_length=200, verbose_name='ticket'),
        ),
        migrations.AlterField(
            model_name='pqr',
            name='type',
            field=models.CharField(choices=[('I', 'Incidente'), ('P', 'Problema'), ('C', 'Consulta'), ('CA', 'Cambio')], default='I', max_length=50, null=True),
        ),
    ]
