# Generated by Django 3.1.2 on 2022-02-25 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lerny', '0030_auto_20220221_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_name', models.CharField(blank=True, max_length=100, verbose_name='interface name')),
            ],
        ),
        migrations.CreateModel(
            name='Interface_Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lerny.company')),
                ('interface_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lerny.interface')),
            ],
        ),
    ]
