# Generated by Django 3.1.2 on 2022-03-09 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lerny', '0031_interface_interface_company'),
        ('lerny', '0031_auto_20220228_0158'),
    ]

    operations = [
    ]
