# Generated by Django 3.1.2 on 2022-03-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lerny', '0032_merge_20220309_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_quiz_logs',
            name='user_quiz_id',
        ),
        migrations.AddField(
            model_name='user_quiz_logs',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
