# Generated by Django 3.1.2 on 2022-03-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lerny', '0033_auto_20220315_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_quiz_logs',
            name='id',
        ),
        migrations.AddField(
            model_name='user_quiz_logs',
            name='user_quiz_id',
            field=models.AutoField(default=15, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
