# Generated by Django 3.1.2 on 2022-03-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lerny', '0033_auto_20220315_1546'),
    ]

    operations = [
        
    ]
