# Generated by Django 3.1.2 on 2022-03-15 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lerny', '0034_user_quiz_logs_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_quiz_logs',
        ),
    ]
