# Generated by Django 3.1.2 on 2022-03-15 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lerny', '0035_delete_user_quiz_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_quiz_logs',
            fields=[
                ('user_quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('response', models.CharField(max_length=300, verbose_name='response ')),
                ('points', models.IntegerField(null=True, verbose_name='points')),
                ('state_quiz', models.BooleanField(default=False, verbose_name='state')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
