# Generated by Django 3.1.2 on 2022-03-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lerny', '0036_user_quiz_logs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='points',
        ),
        migrations.AddField(
            model_name='resource',
            name='points_correct_answer',
            field=models.FloatField(blank=True, default=1, verbose_name='points correct answer'),
        ),
        migrations.AddField(
            model_name='resource',
            name='points_wrong_answer',
            field=models.FloatField(blank=True, default=1, verbose_name='points wrong answer'),
        ),
    ]
