# Generated by Django 3.1.2 on 2022-03-24 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lerny', '0037_auto_20220316_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_quiz_logs',
            old_name='state_quiz',
            new_name='correct',
        ),
        migrations.AddField(
            model_name='user_quiz_logs',
            name='resource_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lerny.resource'),
        ),
    ]
