# Generated by Django 3.1.2 on 2022-04-08 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lerny', '0038_auto_20220324_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='correct_answer',
            new_name='response_answer_correct',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='wrong_answer',
            new_name='response_wrong_answer',
        ),
    ]
