# Generated by Django 3.1.2 on 2020-10-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_name', models.CharField(max_length=50, verbose_name='user name')),
                ('user_surname', models.CharField(max_length=50, verbose_name='user surname')),
                ('country', models.CharField(max_length=20, verbose_name='country')),
                ('city', models.CharField(max_length=20, verbose_name='city')),
                ('passw', models.CharField(max_length=20, verbose_name='passw')),
                ('cellphone_number', models.CharField(max_length=20, unique=True, verbose_name='cellphone number')),
                ('mail', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='mail')),
                ('notification', models.BooleanField(default=True)),
                ('last_view_date', models.DateTimeField(null=True, verbose_name='last view date')),
                ('points', models.FloatField(default=0.0, verbose_name='points')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('active_user', models.BooleanField(default=True)),
                ('admin_user', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
