# Generated by Django 3.1.2 on 2021-05-11 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201118_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(default='', max_length=100, verbose_name='uid'),
        ),
    ]
