# Generated by Django 3.1.2 on 2021-06-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='uid'),
        ),
    ]
