# Generated by Django 3.2.4 on 2021-06-17 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lerny', '0010_company'),
        ('user', '0004_auto_20210610_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lerny.company'),
        ),
    ]
