# Generated by Django 3.1.2 on 2021-07-13 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210627_1340'),
    ]

    operations = [

    ]
