# Generated by Django 3.1.2 on 2021-07-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210712_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.FloatField(blank=True, null=True, verbose_name='points'),
        ),
    ]
